//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoeSbot.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoeSbot.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Info Command.
        /// </summary>
        internal static string audiomodule_audioinfo_name {
            get {
                return ResourceManager.GetString("audiomodule_audioinfo_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can get info about an audio item:
        ///
        ///{fields}
        ///   {field}
        ///      {name}Parameter: The url{/name}
        ///      {value}Provide an url to the audio item{/value}
        ///   {/field}
        ///{/fields}
        ///
        ///{examples}
        ///   {example}{0}{1} https://www.youtube.com/watch?v=P1y1O1o69wA{/example}
        ///{/examples}.
        /// </summary>
        internal static string audiomodule_audioinfo_summary {
            get {
                return ResourceManager.GetString("audiomodule_audioinfo_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Song Command.
        /// </summary>
        internal static string audiomodule_current_name {
            get {
                return ResourceManager.GetString("audiomodule_current_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the current audio item:
        ///
        ///{examples}
        ///   {example}{0}{1}{/example}
        ///{/examples}.
        /// </summary>
        internal static string audiomodule_current_summary {
            get {
                return ResourceManager.GetString("audiomodule_current_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio module.
        /// </summary>
        internal static string audiomodule_name {
            get {
                return ResourceManager.GetString("audiomodule_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Command.
        /// </summary>
        internal static string audiomodule_play_name {
            get {
                return ResourceManager.GetString("audiomodule_play_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can play an audio item:
        ///
        ///{fields}
        ///   {field}
        ///      {name}Parameter: the url{/name}
        ///      {value}Provide an url to the audio item{/value}
        ///   {/field}
        ///{/fields}
        ///
        ///{examples}
        ///   {example}{0}{1} Super mario theme{/example}
        ///{/examples}.
        /// </summary>
        internal static string audiomodule_play_summary {
            get {
                return ResourceManager.GetString("audiomodule_play_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Command.
        /// </summary>
        internal static string audiomodule_skip_name {
            get {
                return ResourceManager.GetString("audiomodule_skip_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can skip an audio item:
        ///
        ///{examples}
        ///   {example}{0}{1}{/example}
        ///{/examples}.
        /// </summary>
        internal static string audiomodule_skip_summary {
            get {
                return ResourceManager.GetString("audiomodule_skip_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Command.
        /// </summary>
        internal static string audiomodule_stop_name {
            get {
                return ResourceManager.GetString("audiomodule_stop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can stop an audio item:
        ///
        ///{examples}
        ///   {example}{0}{1}{/example}
        ///{/examples}.
        /// </summary>
        internal static string audiomodule_stop_summary {
            get {
                return ResourceManager.GetString("audiomodule_stop_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Command.
        /// </summary>
        internal static string audiomodule_volume_name {
            get {
                return ResourceManager.GetString("audiomodule_volume_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set the volume level:
        ///
        ///{fields}
        ///   {field}
        ///      {name}Parameter: a number{/name}
        ///      {value}Provide a number between 1 and 10{/value}
        ///   {/field}
        ///{/fields}
        ///
        ///{examples}
        ///   {example}{0}{1} 2{/example}
        ///{/examples}.
        /// </summary>
        internal static string audiomodule_volume_summary {
            get {
                return ResourceManager.GetString("audiomodule_volume_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string label_example {
            get {
                return ResourceManager.GetString("label_example", resourceCulture);
            }
        }
    }
}
